### ISSUE TITLE
Use the current word if selection is empty

### ISSUE THREAD

**Issue by bizoo** [tehstun/toggler#1]
If selection is empty, toggle the word under or next to the cursor (using API method getWordRangeAtPosition() ?).
This way you don't have to select the word prior executing toggler.

Thanks for this great plugin.

**Comment by tehstun** [comment]
Great stuff, 

I will look into this more later and test it and push it up.

Thanks for the input!

**Comment by bizoo** [comment]
Forgot to tell that I've done the source modifications in github editor and didn't check them after.
So please check them before merging in master branch and pushing worldwide.

There's a small issue, don't know if it's a VSCode bug:
-When you toggle a word without selecting it first, the highlight of current word is not updated (if you change true to false, all true is still highlighted after). You have to move the cursor to update the view.
