### ISSUE TITLE
Weird selection after toggling makes it impossible to toggle anymore

### ISSUE THREAD

**Issue by HiDeoo** [tehstun/toggler#3]
Without a selection, after toggling, some (random) parts of the words get selected making it unable to toggle anymore.

![toggler1](https://user-images.githubusercontent.com/494699/28109906-f85db464-66f0-11e7-89b9-2c5965b27be8.gif)

The selection seems to always happen at the end of the word but the length is not always the same:

* _fals_**e**
* _unlo_**ad**
* _disable_**d**

This does not happens when selecting the word to toggle.

*VSCode v1.14.0*

**Comment by tehstun** [comment]
Hmmm, it's currently only on the cursor being at the end of the word. 

I will see what I can do.

**Comment by tehstun** [comment]
Moved back to previous selection only version for when I have a better time to look into the changes, hopefully over the next two months, until then i'm closing the issues.
