### ISSUE TITLE
Cursor position leads to unexpected or impossible toggles

### ISSUE THREAD

**Issue by HiDeoo** [tehstun/toggler#4]
Without selection, if we take the `test` => `test.only` toggle, the cursor position leads to totally unexpected result.

![toggler2](https://user-images.githubusercontent.com/494699/28110297-3a3e055e-66f2-11e7-888d-a37b822b271b.gif)

*The ^ indicates the cursor position.*

`test` will transform into `test.only`.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

`test.only` will transform into `test.only.only`.
&nbsp;^

`test.only` will not even trigger a toggle.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

`test.only` will not even trigger a toggle.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

`test.only` will transform into `test.only.only`.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^

**Comment by tehstun** [comment]
Vscode Api selects closest word and ignores non alpha characters

I will see what I can do.

**Comment by tehstun** [comment]
Moved back to previous selection only version for when I have a better time to look into the changes, hopefully over the next two months, until then i'm closing the issues.

**Comment by HiDeoo** [comment]
In the meantime, people having this issue or one of the other issues I reported can use [the official port of my Atom package](https://marketplace.visualstudio.com/items?itemName=hideoo.toggler) that I released today on the Marketplace.

**Comment by tehstun** [comment]
Really?
